# 27.03.2026 - Tunnel Configuration File

REMOTE_HOST=lus-2.optnl.com
SSH_USER=opentunnel.net-sshlinux
SSH_PASS= linuxforge
SSH_PORT=443
TUNNEL_PORT=9090 #the port the tunnel runs on
SOCKS_PORT=2070 #the socks proxy port
SNI=aka.ms #add you custom SNI here (optional)
EXPIRES=2025-12-31 # Expiration (optional, format: YYYY-MM-DD)
BLOCKLIST=/path/to/blocklist.txt  # Optional ad-blocking

# Public Key : 9673e27b0ed9d3d11d6d439e24a928d575bb666807b0d088589d339906c58b6d
#DNS Config : 1.1.1.1:9673e27b0ed9d3d11d6d439e24a928d575bb666807b0d088589d339906c58b6d@opentunnel.net-sshlinux:linuxforge@dns.lus-2.optnl.com